# Generated by Django 5.2.7 on 2026-03-09 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advising_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "grade_status",
                    models.CharField(
                        choices=[
                            ("ADVISING", "Advising"),
                            ("ENROLLED", "Enrolled"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("INC", "Incomplete"),
                            ("DROPPED", "Dropped"),
                            ("RETAKE", "Retake"),
                        ],
                        default="ADVISING",
                        max_length=20,
                    ),
                ),
                (
                    "midterm_grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "final_grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("is_credited", models.BooleanField(default=False)),
                ("is_retake", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True)),
                ("inc_deadline", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["student", "subject", "term"],
            },
        ),
    ]
