# Generated by Django 5.2.7 on 2026-03-09 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_alter_program_code_alter_program_effective_year"),
        ("grades", "0001_initial"),
        ("sections", "0001_initial"),
        ("students", "0001_initial"),
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades",
                to="sections.section",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_grades",
                to="academics.subject",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grades",
                to="terms.term",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "subject", "term")},
        ),
    ]
