# Generated by Django 5.2.7 on 2026-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0003_grade_final_submitted_at_grade_finalized_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="grade_status",
            field=models.CharField(
                choices=[
                    ("ADVISING", "Advising"),
                    ("ENROLLED", "Enrolled"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("INC", "Incomplete"),
                    ("DROPPED", "Dropped"),
                    ("RETAKE", "Retake"),
                    ("NO_GRADE", "No Grade"),
                ],
                default="ADVISING",
                max_length=20,
            ),
        ),
    ]
