# Generated by Django 5.2.7 on 2026-03-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0004_alter_grade_grade_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="is_historical",
            field=models.BooleanField(
                default=False,
                help_text="Manually encoded from the student's previous TOR.",
            ),
        ),
    ]
