# Generated by Django 5.2.7 on 2026-03-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0005_grade_is_historical"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="historical_source",
            field=models.CharField(
                blank=True,
                help_text="Reference to the physical TOR or source document.",
                max_length=255,
                null=True,
            ),
        ),
    ]
