# Generated by Django 5.2.7 on 2026-03-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Room 101, Lab 201", max_length=50, unique=True
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("LECTURE", "Lecture Room"),
                            ("COMPUTER_LAB", "Computer Laboratory"),
                            ("SCIENCE_LAB", "Science Laboratory"),
                            ("OTHER", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
