# Generated by Django 5.2.7 on 2026-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="notification_type",
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("ADVISING", "Advising"),
                    ("GRADE", "Grade"),
                    ("FINANCE", "Finance"),
                    ("ENROLLMENT", "Enrollment"),
                    ("SCHEDULE", "Schedule"),
                    ("GENERAL", "General"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="link_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
