# Generated by Django 5.2.7 on 2026-03-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 2027-1, 2027-2, 2027-S",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(help_text="e.g., 2027-2028", max_length=20),
                ),
                (
                    "semester_type",
                    models.CharField(
                        choices=[
                            ("1", "First Semester"),
                            ("2", "Second Semester"),
                            ("S", "Summer"),
                        ],
                        max_length=2,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("enrollment_start", models.DateField()),
                ("enrollment_end", models.DateField()),
                ("advising_start", models.DateField()),
                ("advising_end", models.DateField()),
                ("schedule_picking_start", models.DateField(blank=True, null=True)),
                ("schedule_picking_end", models.DateField(blank=True, null=True)),
                ("midterm_grade_start", models.DateField(blank=True, null=True)),
                ("midterm_grade_end", models.DateField(blank=True, null=True)),
                ("final_grade_start", models.DateField(blank=True, null=True)),
                ("final_grade_end", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-academic_year", "-semester_type"],
            },
        ),
    ]
