# Generated by Django 5.2.7 on 2026-03-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="schedule_published",
            field=models.BooleanField(
                default=False,
                help_text="Dean publishes schedule to open student picking",
            ),
        ),
    ]
