# Generated by Django 5.2.7 on 2026-03-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0002_add_schedule_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="grade_submission_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Hard deadline for all grade submissions",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="is_grades_locked",
            field=models.BooleanField(
                default=False,
                help_text="Global lock: No more grade edits allowed for this term",
            ),
        ),
    ]
