# Generated by Django 5.2.12 on 2026-04-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0003_term_grade_submission_deadline_term_is_grades_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='schedule_picking_end',
        ),
        migrations.RemoveField(
            model_name='term',
            name='schedule_picking_start',
        ),
        migrations.AddField(
            model_name='term',
            name='picking_published_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the Dean published the schedule', null=True),
        ),
    ]
