# Generated by Django 5.2.12 on 2026-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0004_remove_term_schedule_picking_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='schedule_picking_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='schedule_picking_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
