from typing import Any, Dict, Optional
from django.core import signing
from django.conf import settings
from datetime import timedelta
from rest_framework.response import Response
from django.utils import timezone


def api_response(success: bool, data: Optional[Any] = None, error: Optional[Dict] = None, meta: Optional[Dict] = None, status: int = 200) -> Response:
    """
    Standard API response wrapper.

    Payload shape:
    {
      "success": bool,
      "data": object | null,
      "error": { code, message, details } | null,
      "meta": { timestamp, request_id? }
    }
    """
    payload = {
        "success": bool(success),
        "data": data if success else None,
        "error": error if not success else None,
        "meta": meta or {"timestamp": timezone.now().isoformat()}
    }
    return Response(payload, status=status)


# Signing utils for document download tokens
_SIGNING_SALT = getattr(settings, "DOCUMENT_SIGNING_SALT", "richwell-document-download")
_DEFAULT_EXPIRY_HOURS = int(getattr(settings, "DOCUMENT_SIGNED_URL_EXPIRY_HOURS", 24))


def generate_signed_token(document_id: int, expiry_hours: int = None) -> str:
    """
    Generate a signed token for a document id. Token encodes the document id and issued timestamp.
    """
    expiry_hours = expiry_hours or _DEFAULT_EXPIRY_HOURS
    payload = {
        "document_id": int(document_id),
        "issued_at": timezone.now().isoformat(),
        "expiry_hours": int(expiry_hours)
    }
    token = signing.dumps(payload, salt=_SIGNING_SALT)
    return token


def verify_signed_token(token: str) -> Optional[int]:
    """
    Verify a token generated by `generate_signed_token`.
    Returns document_id if valid and not expired, otherwise None.
    """
    try:
        payload = signing.loads(token, salt=_SIGNING_SALT)
        # Check expiry based on issued_at + expiry_hours
        issued = timezone.datetime.fromisoformat(payload.get("issued_at"))
        expiry_hours = int(payload.get("expiry_hours", _DEFAULT_EXPIRY_HOURS))
        expiry = issued + timedelta(hours=expiry_hours)
        if timezone.now() > expiry:
            return None
        return int(payload.get("document_id"))
    except Exception:
        return None
