# Generated by Django 5.2.7 on 2026-03-09 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_alter_program_code_alter_program_effective_year"),
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("year_level", models.PositiveSmallIntegerField()),
                (
                    "session",
                    models.CharField(
                        choices=[("AM", "AM"), ("PM", "PM")], max_length=2
                    ),
                ),
                ("max_students", models.PositiveSmallIntegerField(default=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="academics.program",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="terms.term",
                    ),
                ),
            ],
        ),
    ]
