# Generated by Django 5.2.7 on 2026-03-09 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_alter_program_code_alter_program_effective_year"),
        ("sections", "0001_initial"),
        ("students", "0005_alter_studentenrollment_advising_status"),
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="section",
            name="section_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="section",
            name="target_students",
            field=models.PositiveSmallIntegerField(default=35),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("term", "program", "year_level", "section_number")},
        ),
        migrations.CreateModel(
            name="SectionStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_home_section", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="sections.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_assignments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("section", "student")},
            },
        ),
    ]
