# Generated by Django 5.2.12 on 2026-04-10 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_section_is_active_section_section_number_and_more'),
        ('students', '0010_add_term_to_section_student'),
        ('terms', '0003_term_grade_submission_deadline_term_is_grades_locked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectionstudent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sectionstudent',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_student_assignments', to='terms.term'),
        ),
        migrations.AlterUniqueTogether(
            name='sectionstudent',
            unique_together={('student', 'term')},
        ),
    ]
