# Generated by Django 5.2.9 on 2025-12-09 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ENROLLMENT_CREATED', 'Enrollment Created'), ('ENROLLMENT_UPDATED', 'Enrollment Updated'), ('ENROLLMENT_STATUS_CHANGED', 'Enrollment Status Changed'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('PAYMENT_ADJUSTED', 'Payment Adjusted'), ('PAYMENT_ALLOCATED', 'Payment Allocated'), ('SUBJECT_ENROLLED', 'Subject Enrolled'), ('SUBJECT_DROPPED', 'Subject Dropped'), ('GRADE_SUBMITTED', 'Grade Submitted'), ('GRADE_UPDATED', 'Grade Updated'), ('GRADE_FINALIZED', 'Grade Finalized'), ('INC_CONVERTED_TO_FAILED', 'INC Converted to Failed'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_IMPERSONATED', 'User Impersonated'), ('DOCUMENT_RELEASED', 'Document Released'), ('DOCUMENT_REVOKED', 'Document Revoked'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('SCHEDULE_CONFLICT_OVERRIDE', 'Schedule Conflict Override'), ('CREDIT_ASSIGNED', 'Credit Assigned'), ('CREDIT_REMOVED', 'Credit Removed'), ('CONFIG_CHANGED', 'Configuration Changed'), ('SYSTEM_EVENT', 'System Event')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('target_model', models.CharField(db_index=True, help_text='Model name of the affected object', max_length=100)),
                ('target_id', models.UUIDField(blank=True, db_index=True, help_text='ID of the affected object', null=True)),
                ('payload', models.JSONField(default=dict, help_text='Additional details: before/after states, reason, metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (null for system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', 'timestamp'], name='audit_audit_actor_i_6355cc_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['target_model', 'target_id'], name='audit_audit_target__573821_idx')],
            },
        ),
    ]
