# Generated by Django 5.2.9 on 2026-01-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("ENROLLMENT_CREATED", "Enrollment Created"),
                    ("ENROLLMENT_UPDATED", "Enrollment Updated"),
                    ("ENROLLMENT_STATUS_CHANGED", "Enrollment Status Changed"),
                    ("PAYMENT_RECORDED", "Payment Recorded"),
                    ("PAYMENT_ADJUSTED", "Payment Adjusted"),
                    ("PAYMENT_ALLOCATED", "Payment Allocated"),
                    ("SUBJECT_ENROLLED", "Subject Enrolled"),
                    ("SUBJECT_DROPPED", "Subject Dropped"),
                    ("SUBJECT_EDITED", "Subject Enrollment Edited"),
                    ("GRADE_SUBMITTED", "Grade Submitted"),
                    ("GRADE_UPDATED", "Grade Updated"),
                    ("GRADE_FINALIZED", "Grade Finalized"),
                    ("INC_CONVERTED_TO_FAILED", "INC Converted to Failed"),
                    ("USER_CREATED", "User Created"),
                    ("USER_UPDATED", "User Updated"),
                    ("USER_LOGIN", "User Login"),
                    ("USER_LOGOUT", "User Logout"),
                    ("USER_IMPERSONATED", "User Impersonated"),
                    ("DOCUMENT_RELEASED", "Document Released"),
                    ("DOCUMENT_REVOKED", "Document Revoked"),
                    ("DOCUMENT_REISSUED", "Document Reissued"),
                    ("DOCUMENT_ACCESSED", "Document Accessed"),
                    ("DOCUMENT_VERIFIED", "Document Verified"),
                    ("SCHEDULE_CONFLICT_OVERRIDE", "Schedule Conflict Override"),
                    ("CREDIT_ASSIGNED", "Credit Assigned"),
                    ("CREDIT_REMOVED", "Credit Removed"),
                    ("CURRICULUM_CHANGED", "Curriculum Changed"),
                    ("CURRICULUM_VERSION_CREATED", "Curriculum Version Created"),
                    ("SECTION_CREATED", "Section Created"),
                    ("SECTION_UPDATED", "Section Updated"),
                    ("CONFIG_CHANGED", "Configuration Changed"),
                    ("SYSTEM_EVENT", "System Event"),
                    ("OVERRIDE_APPLIED", "Override Applied"),
                    ("EXAM_PERMIT_GENERATED", "Exam Permit Generated"),
                    ("EXAM_PERMIT_PRINTED", "Exam Permit Printed"),
                    ("RECORD_CREATED", "Record Created"),
                    ("RECORD_UPDATED", "Record Updated"),
                    ("RECORD_DELETED", "Record Deleted"),
                    ("PROGRAM_CREATED", "Program Created"),
                    ("PROGRAM_UPDATED", "Program Updated"),
                    ("PROGRAM_DELETED", "Program Deleted"),
                    ("SUBJECT_CREATED", "Subject Created"),
                    ("SUBJECT_UPDATED", "Subject Updated"),
                    ("SUBJECT_DELETED", "Subject Deleted"),
                    ("CURRICULUM_CREATED", "Curriculum Created"),
                    ("CURRICULUM_UPDATED", "Curriculum Updated"),
                    ("CURRICULUM_DELETED", "Curriculum Deleted"),
                    ("SEMESTER_CREATED", "Semester Created"),
                    ("SEMESTER_UPDATED", "Semester Updated"),
                    ("SEMESTER_DELETED", "Semester Deleted"),
                    ("SEMESTER_SET_CURRENT", "Semester Set as Current"),
                    ("SECTION_DELETED", "Section Deleted"),
                ],
                db_index=True,
                help_text="Type of action performed",
                max_length=50,
            ),
        ),
    ]
