# Generated by Django 5.2.7 on 2026-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="amount_paid",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="month_number",
            new_name="month",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="is_adjustment",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_date",
        ),
        migrations.AddField(
            model_name="payment",
            name="entry_type",
            field=models.CharField(
                choices=[("PAYMENT", "Payment"), ("ADJUSTMENT", "Adjustment")],
                default="PAYMENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
