# Generated by Django 5.2.7 on 2026-03-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="reference_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
