# Generated by Django 5.2.7 on 2026-03-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_payment_reference_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="remarks",
            new_name="notes",
        ),
    ]
