# Generated by Django 5.2.7 on 2026-03-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("LOGIN_FAILED", "Login Failed"),
                ],
                max_length=15,
            ),
        ),
    ]
