# Generated by Django 5.2.12 on 2026-04-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('BULK_IMPORT', 'Bulk Import'), ('RELEASE', 'Document Released'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset')], max_length=20),
        ),
    ]
