# Generated by Django 5.2.12 on 2026-04-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0003_audit_coverage_expansion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('BULK_IMPORT', 'Bulk Import'), ('RELEASE', 'Document Released'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('UNIT_LIMIT_OVERRIDE', 'Unit Limit Override'), ('ADVISING_APPROVE', 'Advising Approved'), ('ADVISING_REJECT', 'Advising Rejected'), ('CREDITING_APPROVE', 'Crediting Approved'), ('CREDITING_REJECT', 'Crediting Rejected')], max_length=20),
        ),
    ]
