# Generated by Django 4.2.13 on 2025-12-03 15:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("PROFESSOR", "Professor"),
                            ("REGISTRAR", "Registrar"),
                            ("HEAD_REGISTRAR", "Head Registrar"),
                            ("CASHIER", "Cashier"),
                            ("ADMIN", "Admin"),
                            ("ADMISSION_STAFF", "Admission Staff"),
                        ],
                        default="STUDENT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sis_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.CharField(max_length=9, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sis_academicyear",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("target_model", models.CharField(max_length=50)),
                ("target_id", models.CharField(max_length=50)),
                ("payload", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "sis_auditlog",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_school", models.CharField(max_length=255)),
                ("original_subject_code", models.CharField(max_length=50)),
                (
                    "original_grade",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("tor_document_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sis_creditsource",
                "ordering": ["subject_enrollment"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("TOR", "Transcript of Records"),
                            ("COE", "Certificate of Enrollment"),
                            ("CGM", "Certificate of Good Moral"),
                            ("DIP", "Diploma"),
                            ("HD", "Honorable Dismissal"),
                            ("OTH", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("release_date", models.DateField(auto_now_add=True)),
                ("protected_url", models.URLField()),
                ("revoked", models.BooleanField(default=False)),
                ("revocation_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sis_documentrelease",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("LOA", "Leave of Absence"),
                            ("GRADUATED", "Graduated"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("first_month_paid", models.BooleanField(default=False)),
                (
                    "monthly_commitment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online Enrollment"),
                            ("TRANSFEREE", "Transferee"),
                            ("MANUAL", "Manual"),
                        ],
                        default="ONLINE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sis_enrollment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamMonthMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("PRELIM", "Preliminary Exam"),
                            ("MIDTERM", "Midterm Exam"),
                            ("PREFINAL", "Prefinal Exam"),
                            ("FINAL", "Final Exam"),
                        ],
                        max_length=20,
                    ),
                ),
                ("month_number", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sis_exammonthmapping",
                "ordering": ["semester", "exam_type"],
            },
        ),
        migrations.CreateModel(
            name="ExamPermit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("PRELIM", "Preliminary Exam"),
                            ("MIDTERM", "Midterm Exam"),
                            ("PREFINAL", "Prefinal Exam"),
                            ("FINAL", "Final Exam"),
                        ],
                        max_length=20,
                    ),
                ),
                ("month_number", models.IntegerField()),
                ("permit_code", models.CharField(max_length=50, unique=True)),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sis_exampermit",
                "ordering": ["enrollment", "exam_type"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        blank=True,
                        choices=[
                            (1.0, "1.0 - Excellent"),
                            (1.25, "1.25 - Very Good"),
                            (1.5, "1.5 - Very Good"),
                            (1.75, "1.75 - Good"),
                            (2.0, "2.0 - Good"),
                            (2.25, "2.25 - Satisfactory"),
                            (2.5, "2.5 - Satisfactory"),
                            (2.75, "2.75 - Passing"),
                            (3.0, "3.0 - Passing"),
                            (5.0, "5.0 - Failed"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "special_grade",
                    models.CharField(
                        blank=True,
                        choices=[("INC", "Incomplete"), ("DRP", "Dropped")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_finalized", models.BooleanField(default=False)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("inc_marked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sis_grade",
                "ordering": ["subject_enrollment"],
            },
        ),
        migrations.CreateModel(
            name="GradeHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_value", models.CharField(blank=True, max_length=20, null=True)),
                ("new_value", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sis_gradehistory",
                "ordering": ["grade", "-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyPaymentBucket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month_number", models.IntegerField()),
                (
                    "required_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_fully_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sis_monthlypaymentbucket",
                "ordering": ["enrollment", "month_number"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "Payment"),
                            ("PERMIT_UNLOCKED", "Permit Unlocked"),
                            ("INC_WARNING", "INC Warning"),
                            ("INC_EXPIRY", "INC Expiry"),
                            ("GRADE_POSTED", "Grade Posted"),
                            ("ENROLLMENT", "Enrollment"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sis_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("ONLINE", "Online"),
                            ("CHECK", "Check"),
                        ],
                        max_length=20,
                    ),
                ),
                ("allocated_to_month", models.IntegerField()),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("receipt_url", models.URLField(blank=True, null=True)),
                ("is_adjustment", models.BooleanField(default=False)),
                ("adjustment_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sis_paymenttransaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sis_program",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("capacity", models.IntegerField()),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sis_section",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SectionSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_tba", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "professor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="section_subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_subjects",
                        to="sis.section",
                    ),
                ),
            ],
            options={
                "db_table": "sis_sectionsubject",
                "ordering": ["section", "subject"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        choices=[(1, "1st Semester"), (2, "2nd Semester")]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("enrollment_deadline", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="semesters",
                        to="sis.academicyear",
                    ),
                ),
            ],
            options={
                "db_table": "sis_semester",
                "ordering": ["-academic_year", "-number"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_number", models.CharField(max_length=20, unique=True)),
                ("year_level", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("LOA", "Leave of Absence"),
                            ("GRADUATED", "Graduated"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="sis.program",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sis_student",
                "ordering": ["student_number"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("units", models.IntegerField()),
                ("is_major", models.BooleanField(default=True)),
                ("year_level", models.IntegerField()),
                (
                    "semester_number",
                    models.IntegerField(
                        choices=[(1, "1st Semester"), (2, "2nd Semester")]
                    ),
                ),
                ("allow_multiple_sections", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True, related_name="dependent_subjects", to="sis.subject"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="sis.program",
                    ),
                ),
            ],
            options={
                "db_table": "sis_subject",
                "ordering": ["program", "year_level", "semester_number", "code"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sis_systemconfig",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="sis.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="sis.student",
                    ),
                ),
            ],
            options={
                "db_table": "sis_transcript",
                "ordering": ["-semester"],
            },
        ),
        migrations.CreateModel(
            name="SubjectEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENROLLED", "Enrolled"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("INC", "Incomplete"),
                            ("DROPPED", "Dropped"),
                            ("CREDITED", "Credited"),
                            ("RETAKE", "Retake"),
                        ],
                        default="ENROLLED",
                        max_length=20,
                    ),
                ),
                ("is_irregular", models.BooleanField(default=False)),
                ("count_in_gpa", models.BooleanField(default=True)),
                ("units", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_enrollments",
                        to="sis.enrollment",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_enrollments",
                        to="sis.sectionsubject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="sis.subject",
                    ),
                ),
            ],
            options={
                "db_table": "sis_subjectenrollment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="sectionsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_subjects",
                to="sis.subject",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="sis.semester",
            ),
        ),
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                            ("SUN", "Sunday"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("room", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_slots",
                        to="sis.sectionsubject",
                    ),
                ),
            ],
            options={
                "db_table": "sis_scheduleslot",
                "ordering": ["section_subject", "day", "start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["code"], name="sis_program_code_d0dc94_idx"),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(
                fields=["is_active"], name="sis_program_is_acti_7d1b51_idx"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="cashier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_recorded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_transactions",
                to="sis.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="monthlypaymentbucket",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_payment_buckets",
                to="sis.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="gradehistory",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grade_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gradehistory",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="sis.grade",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="professor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="subject_enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade",
                to="sis.subjectenrollment",
            ),
        ),
        migrations.AddField(
            model_name="exampermit",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_permits",
                to="sis.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="exammonthmapping",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_mappings",
                to="sis.semester",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="sis.program",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="sis.semester",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="sis.student",
            ),
        ),
        migrations.AddField(
            model_name="documentrelease",
            name="released_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_released",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentrelease",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_releases",
                to="sis.student",
            ),
        ),
        migrations.AddField(
            model_name="creditsource",
            name="subject_enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_source",
                to="sis.subjectenrollment",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transcript",
            unique_together={("student", "semester")},
        ),
        migrations.AddIndex(
            model_name="subjectenrollment",
            index=models.Index(
                fields=["enrollment", "status"], name="sis_subject_enrollm_e01389_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectenrollment",
            index=models.Index(
                fields=["subject", "status"], name="sis_subject_subject_497bdc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectenrollment",
            unique_together={("enrollment", "subject")},
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["program", "code"], name="sis_subject_program_9507c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["is_active"], name="sis_subject_is_acti_cab34f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("program", "code")},
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["student_number"], name="sis_student_student_4ee1d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["program", "status"], name="sis_student_program_44aabd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="semester",
            index=models.Index(
                fields=["academic_year", "is_active"],
                name="sis_semeste_academi_d49d27_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("academic_year", "number")},
        ),
        migrations.AddIndex(
            model_name="sectionsubject",
            index=models.Index(
                fields=["section", "subject"], name="sis_section_section_ada1d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionsubject",
            index=models.Index(
                fields=["professor"], name="sis_section_profess_5d4ed4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sectionsubject",
            unique_together={("section", "subject")},
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["semester", "code"], name="sis_section_semeste_bf1aa0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("semester", "code")},
        ),
        migrations.AddIndex(
            model_name="scheduleslot",
            index=models.Index(
                fields=["section_subject", "day"], name="sis_schedul_section_58333e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["enrollment"], name="sis_payment_enrollm_61a5d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["receipt_number"], name="sis_payment_receipt_e43a78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["created_at"], name="sis_payment_created_7d3c02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="sis_notific_user_id_33e23b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="sis_notific_created_f38678_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlypaymentbucket",
            index=models.Index(
                fields=["enrollment", "is_fully_paid"],
                name="sis_monthly_enrollm_61d6ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlypaymentbucket",
            index=models.Index(
                fields=["enrollment", "month_number"],
                name="sis_monthly_enrollm_9e17c1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthlypaymentbucket",
            unique_together={("enrollment", "month_number")},
        ),
        migrations.AddIndex(
            model_name="gradehistory",
            index=models.Index(
                fields=["grade", "changed_at"], name="sis_gradehi_grade_i_792cb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["subject_enrollment"], name="sis_grade_subject_ce634b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["is_finalized"], name="sis_grade_is_fina_0960ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exampermit",
            index=models.Index(
                fields=["enrollment", "exam_type"],
                name="sis_examper_enrollm_ef207b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exampermit",
            index=models.Index(
                fields=["permit_code"], name="sis_examper_permit__6d128a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exammonthmapping",
            unique_together={("semester", "exam_type")},
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "semester"], name="sis_enrollm_student_4ebbff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["semester", "status"], name="sis_enrollm_semeste_1eb4bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["first_month_paid"], name="sis_enrollm_first_m_215457_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "semester")},
        ),
        migrations.AddIndex(
            model_name="documentrelease",
            index=models.Index(
                fields=["student", "document_type"],
                name="sis_documen_student_2377b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentrelease",
            index=models.Index(
                fields=["created_at"], name="sis_documen_created_ece0e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor", "created_at"], name="sis_auditlo_actor_i_cf61a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_model", "target_id"],
                name="sis_auditlo_target__99ba3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="sis_auditlo_action_94daf5_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["created_at"], name="sis_auditlo_created_7683fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="sis_user_email_19c6aa_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="sis_user_role_dd53be_idx"),
        ),
    ]
