# Generated by Django 5.1.4 on 2025-11-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectenrollment",
            name="inc_start_date",
            field=models.DateField(
                blank=True, help_text="Date when INC status was assigned", null=True
            ),
        ),
        migrations.AddField(
            model_name="subjectenrollment",
            name="loa_pause_days",
            field=models.IntegerField(
                default=0, help_text="Total days LOA paused INC clock"
            ),
        ),
    ]
