# Generated by Django 5.2.9 on 2025-12-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_standing',
            field=models.CharField(blank=True, default='', help_text="Academic standing (e.g., Good Standing, Dean's List, Probation)", max_length=100),
        ),
    ]
