# Generated by Django 5.2.7 on 2026-03-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="must_change_password",
        ),
    ]
