# Generated by Django 5.2.9 on 2025-12-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_epic5_grade_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("PROFESSOR", "Professor"),
                    ("CASHIER", "Cashier"),
                    ("REGISTRAR", "Registrar"),
                    ("HEAD_REGISTRAR", "Head Registrar"),
                    ("ADMISSION_STAFF", "Admission Staff"),
                    ("DEPARTMENT_HEAD", "Department Head"),
                    ("ADMIN", "Admin"),
                ],
                default="STUDENT",
                help_text="User role for access control",
                max_length=20,
            ),
        ),
    ]
