# Generated by Django 5.2.9 on 2025-12-25 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_add_curriculum_models"),
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="curriculum",
            field=models.ForeignKey(
                blank=True,
                help_text="The curriculum version the student is following",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="academics.curriculum",
            ),
        ),
    ]
