# Generated by Django 5.2.9 on 2026-01-24 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_permission_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Unique reset token sent via email",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Token expiration time (1 hour from creation)"
                    ),
                ),
                (
                    "used",
                    models.BooleanField(
                        default=False, help_text="Whether this token has been used"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, help_text="When the token was used", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting password reset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["token", "used", "expires_at"],
                        name="accounts_pa_token_ce83f0_idx",
                    )
                ],
            },
        ),
    ]
