# Generated by Django 5.2.9 on 2026-01-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_subject_syllabus"),
        ("accounts", "0007_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="professorprofile",
            name="assigned_subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects this professor is qualified/assigned to teach",
                related_name="qualified_professors",
                to="academics.subject",
            ),
        ),
    ]
