# Generated by Django 5.2.9 on 2026-01-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0013_section_is_dissolved_section_parent_section_and_more"),
        ("accounts", "0008_professorprofile_assigned_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="academic_status",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular"),
                    ("PROBATION", "Probation"),
                    ("DISMISSED", "Dismissed"),
                ],
                default="REGULAR",
                help_text="Academic standing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="home_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Administrative home section for regular students",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_students",
                to="academics.section",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="is_irregular",
            field=models.BooleanField(
                default=False, help_text="Whether the student is an irregular student"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="max_units_override",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Override for maximum units (default is 24)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="overload_approved",
            field=models.BooleanField(
                default=False, help_text="Whether overload is approved by registrar"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("LOA", "Leave of Absence"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("GRADUATED", "Graduated"),
                ],
                default="ACTIVE",
                help_text="Enrollment status (Active, LOA, etc.)",
                max_length=20,
            ),
        ),
    ]
