# Generated by Django 5.2.7 on 2026-02-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_studentprofile_academic_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermission",
            name="scope",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Fine-grained scope for this permission (e.g., {"permitted_roles": ["REGISTRAR"]})',
            ),
        ),
    ]
