# Generated by Django 5.2.7 on 2026-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0019_scheduleslot_color"),
        ("accounts", "0010_userpermission_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="professorprofile",
            name="programs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Programs/Departments this professor belongs to or teaches in",
                related_name="professors",
                to="academics.program",
            ),
        ),
    ]
