# Generated by Django 5.2.7 on 2026-02-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_professorprofile_programs"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="is_past_student",
            field=models.BooleanField(
                default=False,
                help_text="Whether the student is a past student (returnee)",
            ),
        ),
    ]
