# Generated by Django 5.2.7 on 2026-02-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_studentprofile_is_past_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("LOA", "Leave of Absence"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("GRADUATED", "Graduated"),
                    ("INACTIVE", "Inactive"),
                ],
                default="ACTIVE",
                help_text="Enrollment status (Active, LOA, etc.)",
                max_length=20,
            ),
        ),
    ]
