# Generated by Django 5.2.7 on 2026-02-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_studentprofile_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
