# Generated by Django 5.2.7 on 2026-02-21 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0021_alter_room_room_type"),
        ("accounts", "0014_alter_studentprofile_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentHeadProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "programs",
                    models.ManyToManyField(
                        help_text="Programs this department head manages",
                        related_name="department_heads",
                        to="academics.program",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "DEPARTMENT_HEAD"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_head_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Head Profile",
                "verbose_name_plural": "Department Head Profiles",
            },
        ),
    ]
