# Generated by Django 5.2.7 on 2026-02-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_departmentheadprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="is_working_student",
            field=models.BooleanField(
                default=False, help_text="Whether the student is a working student"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="occupational_details",
            field=models.TextField(
                blank=True, help_text="Details about the student's job or work schedule"
            ),
        ),
    ]
