# Generated by Django 5.2.7 on 2026-02-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_studentprofile_is_working_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="is_working_student",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="occupational_details",
        ),
    ]
