# Generated by Django 5.2.7 on 2026-02-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_remove_studentprofile_is_working_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="max_units_override",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Override for maximum units (default is 30)",
                null=True,
            ),
        ),
    ]
