# Generated by Django 5.2.7 on 2026-03-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_studentprofile_max_units_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="preferred_shift",
            field=models.CharField(
                choices=[
                    ("AM", "Morning (AM)"),
                    ("PM", "Afternoon (PM)"),
                    ("NO_PREFERENCE", "No Preference"),
                ],
                default="NO_PREFERENCE",
                help_text="Student preferred time-of-day shift for classes",
                max_length=15,
            ),
        ),
    ]
