# Generated by Django 5.2.7 on 2026-03-07 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "effective_year",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("has_summer", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "program_head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CurriculumVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_name", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_versions",
                        to="academics.program",
                    ),
                ),
            ],
            options={
                "unique_together": {("program", "version_name")},
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=300)),
                ("year_level", models.PositiveIntegerField()),
                ("semester", models.CharField(max_length=2)),
                ("lec_units", models.PositiveIntegerField(default=0)),
                ("lab_units", models.PositiveIntegerField(default=0)),
                ("total_units", models.PositiveIntegerField()),
                (
                    "hrs_per_week",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("is_major", models.BooleanField(default=False)),
                ("is_practicum", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="academics.curriculumversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectPrerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prerequisite_type",
                    models.CharField(
                        choices=[
                            ("SPECIFIC", "Specific Subject"),
                            ("YEAR_STANDING", "Year Standing"),
                            ("ALL_MAJOR", "All Major Subjects"),
                            ("PROGRAM_PERCENTAGE", "Program Percentage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("standing_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "prerequisite_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="is_prerequisite_for",
                        to="academics.subject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="academics.subject",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["curriculum", "year_level", "semester"],
                name="academics_s_curricu_1b68b5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("curriculum", "code")},
        ),
    ]
