# Generated by Django 5.2.9 on 2025-12-09 12:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('code', models.CharField(help_text='Short code (e.g., BSIT, BSCS)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full program name (e.g., Bachelor of Science in Information Technology)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Program description and overview')),
                ('duration_years', models.PositiveIntegerField(default=4, help_text='Normal duration of the program in years', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the program is currently offered')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('code', models.CharField(help_text='Subject code (e.g., CS101, MATH1)', max_length=20)),
                ('title', models.CharField(help_text='Subject title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Subject description')),
                ('units', models.PositiveIntegerField(help_text='Number of units (typically 1-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('is_major', models.BooleanField(default=False, help_text='Whether this is a major subject (affects INC expiry: 6 months for major, 1 year for minor)')),
                ('year_level', models.PositiveIntegerField(help_text='Recommended year level for this subject', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('semester_number', models.PositiveIntegerField(help_text='Recommended semester (1 = First, 2 = Second, 3 = Summer)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('allow_multiple_sections', models.BooleanField(default=False, help_text='Whether a student can enroll in multiple sections (for irregular students)')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Subjects that must be completed before taking this subject', related_name='required_for', to='academics.subject')),
                ('program', models.ForeignKey(help_text='The program this subject belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.program')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['year_level', 'semester_number', 'code'],
                'unique_together': {('program', 'code')},
            },
        ),
    ]
