# Generated by Django 5.2.7 on 2026-03-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="effective_year",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
