# Generated by Django 5.2.7 on 2026-03-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_alter_program_code_alter_program_effective_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectprerequisite",
            name="min_subjects",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subjectprerequisite",
            name="min_units",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subjectprerequisite",
            name="prerequisite_type",
            field=models.CharField(
                choices=[
                    ("SPECIFIC", "Specific Subject"),
                    ("YEAR_STANDING", "Year Standing"),
                    ("ALL_MAJOR", "All Major Subjects"),
                    ("PROGRAM_PERCENTAGE", "Program Percentage"),
                    ("GROUP", "Subject Group"),
                    ("PERCENTAGE", "Units Percentage"),
                ],
                max_length=20,
            ),
        ),
    ]
