# Generated by Django 5.2.9 on 2025-12-10 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_section_sectionsubject_scheduleslot'),
        ('enrollment', '0002_subjectenrollment_creditsource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('version_number', models.PositiveIntegerField(default=1, help_text='Version number for this semester')),
                ('subjects_snapshot', models.JSONField(help_text='JSON snapshot of subjects and prerequisites at the time of version creation')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the active curriculum version for the semester')),
                ('notes', models.TextField(blank=True, help_text='Notes about this curriculum version')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_versions_created', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_versions', to='academics.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_versions', to='enrollment.semester')),
            ],
            options={
                'verbose_name': 'Curriculum Version',
                'verbose_name_plural': 'Curriculum Versions',
                'ordering': ['-semester', '-version_number'],
                'unique_together': {('program', 'semester', 'version_number')},
            },
        ),
    ]
