# Generated by Django 5.2.9 on 2025-12-25 05:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_curriculumversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Curriculum code (e.g., REV3, 2023, K12)",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Curriculum name (e.g., BSIS Revision 3, BSIT Curriculum 2023)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this curriculum version"
                    ),
                ),
                (
                    "effective_year",
                    models.PositiveIntegerField(
                        help_text="Year this curriculum became effective"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether new students can be assigned to this curriculum",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="The program this curriculum belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curricula",
                        to="academics.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curriculum",
                "verbose_name_plural": "Curricula",
                "ordering": ["-effective_year", "code"],
                "unique_together": {("program", "code")},
            },
        ),
        migrations.CreateModel(
            name="CurriculumSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "year_level",
                    models.PositiveIntegerField(
                        help_text="Year level for this subject (1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "semester_number",
                    models.PositiveIntegerField(
                        help_text="Semester number (1 = First, 2 = Second, 3 = Summer)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is a required subject (vs elective)",
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        help_text="The curriculum this assignment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_subjects",
                        to="academics.curriculum",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject being assigned",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_assignments",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curriculum Subject",
                "verbose_name_plural": "Curriculum Subjects",
                "ordering": ["year_level", "semester_number", "subject__code"],
                "unique_together": {("curriculum", "subject")},
            },
        ),
    ]
