# Generated by Django 5.2.12 on 2026-04-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_subjectprerequisite_min_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.CharField(choices=[('SHS', 'Senior High School'), ('CHED', 'College (CHED)'), ('TECHVOC', 'Technical Vocational (Diploma)')], default='CHED', help_text='Academic level for reporting and monitoring.', max_length=10),
        ),
    ]
