# Generated by Django 5.2.9 on 2025-12-25 05:25

from django.db import migrations


def create_default_curricula(apps, schema_editor):
    """
    For each program, create a default curriculum containing
    all existing subjects in their current year/semester assignments.
    """
    Program = apps.get_model('academics', 'Program')
    Curriculum = apps.get_model('academics', 'Curriculum')
    CurriculumSubject = apps.get_model('academics', 'CurriculumSubject')
    Subject = apps.get_model('academics', 'Subject')

    programs = Program.objects.filter(is_deleted=False)

    for program in programs:
        # Create default curriculum
        curriculum = Curriculum.objects.create(
            program=program,
            code="DEFAULT",
            name=f"{program.code} Default Curriculum",
            description="Migrated from existing subject assignments",
            effective_year=2024,
            is_active=True,
            is_deleted=False
        )

        # Copy all subjects with their current year/semester
        subjects = Subject.objects.filter(
            program=program,
            is_deleted=False
        )

        for subject in subjects:
            CurriculumSubject.objects.create(
                curriculum=curriculum,
                subject=subject,
                year_level=subject.year_level,
                semester_number=subject.semester_number,
                is_required=True,
                is_deleted=False
            )

        print(f"Created default curriculum for {program.code} with {subjects.count()} subjects")


def assign_students_to_curriculum(apps, schema_editor):
    """
    Assign all existing students to their program's default curriculum.
    """
    StudentProfile = apps.get_model('accounts', 'StudentProfile')
    Curriculum = apps.get_model('academics', 'Curriculum')

    students = StudentProfile.objects.filter(
        is_deleted=False,
        curriculum__isnull=True
    )

    for student in students:
        default_curriculum = Curriculum.objects.filter(
            program=student.program,
            code="DEFAULT",
            is_deleted=False
        ).first()

        if default_curriculum:
            student.curriculum = default_curriculum
            student.save()
            print(f"Assigned student {student.user.student_number} to {default_curriculum.code}")


def reverse_func(apps, schema_editor):
    """
    Reverse the migration by removing default curricula.
    """
    Curriculum = apps.get_model('academics', 'Curriculum')
    Curriculum.objects.filter(code="DEFAULT").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_add_curriculum_models"),
        ("accounts", "0004_add_curriculum_to_student"),
    ]

    operations = [
        migrations.RunPython(create_default_curricula, reverse_func),
        migrations.RunPython(assign_students_to_curriculum, migrations.RunPython.noop),
    ]
