# Generated by Django 5.2.9 on 2025-12-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_create_default_curricula"),
        ("enrollment", "0009_monthlypaymentbucket_event_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculumsubject",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Bind this subject to a specific semester instance for date-based enrollment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curriculum_assignments",
                to="enrollment.semester",
            ),
        ),
    ]
