# Generated by Django 5.2.9 on 2025-12-26 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_add_semester_to_curriculum_subject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionSubjectProfessor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary/lead professor for this section-subject",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={"role": "PROFESSOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_subject_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professor_assignments",
                        to="academics.sectionsubject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section Subject Professor",
                "verbose_name_plural": "Section Subject Professors",
                "ordering": ["-is_primary", "professor__last_name"],
                "unique_together": {("section_subject", "professor")},
            },
        ),
    ]
