# Generated by Django 5.2.9 on 2025-12-26 15:36

from django.db import migrations


def migrate_professors_to_junction_table(apps, schema_editor):
    """
    Migrate existing professor assignments from SectionSubject.professor
    to the new SectionSubjectProfessor junction table.
    """
    SectionSubject = apps.get_model('academics', 'SectionSubject')
    SectionSubjectProfessor = apps.get_model('academics', 'SectionSubjectProfessor')

    # Get all section_subjects that have a professor assigned
    section_subjects_with_professor = SectionSubject.objects.filter(
        professor__isnull=False,
        is_deleted=False
    ).select_related('professor')

    # Create junction table entries
    for ss in section_subjects_with_professor:
        # Create the assignment with is_primary=True since they were the only professor
        SectionSubjectProfessor.objects.create(
            section_subject=ss,
            professor=ss.professor,
            is_primary=True
        )

    print(f"Migrated {section_subjects_with_professor.count()} professor assignments to junction table.")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - copy primary professors back to SectionSubject.professor
    """
    SectionSubject = apps.get_model('academics', 'SectionSubject')
    SectionSubjectProfessor = apps.get_model('academics', 'SectionSubjectProfessor')

    # Get all primary professor assignments
    primary_assignments = SectionSubjectProfessor.objects.filter(
        is_primary=True,
        is_deleted=False
    ).select_related('section_subject', 'professor')

    for assignment in primary_assignments:
        assignment.section_subject.professor = assignment.professor
        assignment.section_subject.save()

    print(f"Reversed {primary_assignments.count()} professor assignments back to SectionSubject.")


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_sectionsubjectprofessor"),
    ]

    operations = [
        migrations.RunPython(migrate_professors_to_junction_table, reverse_migration),
    ]
