# Generated by Django 5.2.9 on 2025-12-28 04:05

from django.db import migrations, models


def populate_programs(apps, schema_editor):
    """Populate programs field with each subject's primary program"""
    Subject = apps.get_model('academics', 'Subject')
    for subject in Subject.objects.all():
        subject.programs.add(subject.program)


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_migrate_professor_data"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subject",
            name="programs",
            field=models.ManyToManyField(
                blank=True,
                help_text="All programs this subject belongs to (includes primary program)",
                related_name="multi_program_subjects",
                to="academics.program",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("code",),
                name="unique_subject_code",
                violation_error_message="Subject code must be globally unique",
            ),
        ),
        migrations.RunPython(populate_programs, migrations.RunPython.noop),
    ]
