# Generated by Django 5.2.9 on 2026-01-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_add_subject_programs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleslot",
            name="day",
            field=models.CharField(
                choices=[
                    ("MON", "Monday"),
                    ("TUE", "Tuesday"),
                    ("WED", "Wednesday"),
                    ("THU", "Thursday"),
                    ("FRI", "Friday"),
                    ("SAT", "Saturday"),
                    ("SUN", "Sunday"),
                ],
                max_length=3,
            ),
        ),
    ]
