# Generated by Django 5.2.9 on 2026-01-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_add_sunday_to_schedule_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="syllabus",
            field=models.FileField(
                blank=True,
                help_text="Syllabus file for this subject",
                null=True,
                upload_to="syllabi/%Y/%m/",
            ),
        ),
    ]
