# Generated by Django 5.2.9 on 2026-01-24 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_subject_syllabus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleslot",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "PROFESSOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedule_slots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
