# Generated by Django 5.2.9 on 2026-01-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0012_scheduleslot_professor"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="is_dissolved",
            field=models.BooleanField(
                default=False,
                help_text="Whether this section has been dissolved/merged",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="parent_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent section if this section was merged into another",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_sections",
                to="academics.section",
            ),
        ),
        migrations.AddField(
            model_name="sectionsubject",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Subject capacity (defaults to section capacity if null)",
                null=True,
            ),
        ),
    ]
