# Generated by Django 5.2.9 on 2026-01-26 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0013_section_is_dissolved_section_parent_section_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="curriculum",
            field=models.ForeignKey(
                help_text="The curriculum followed by this section (used to auto-link subjects)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections",
                to="academics.curriculum",
            ),
        ),
    ]
