# Generated by Django 5.2.9 on 2026-01-26 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0014_section_curriculum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Room name or number (e.g., Room 101, Lab 1)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=40, help_text="Maximum student capacity"
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("LECTURE", "Lecture Room"),
                            ("LABORATORY", "Laboratory"),
                            ("FUNCTION", "Function Room"),
                            ("OTHER", "Other"),
                        ],
                        default="LECTURE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "ordering": ["name"],
            },
        ),
    ]
