# Generated by Django 5.2.9 on 2026-02-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0016_section_archived_at_section_archived_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="classification",
            field=models.CharField(
                choices=[
                    ("PROFESSIONAL", "Professional (Major)"),
                    ("GENERAL_EDUCATION", "General Education"),
                    ("ELECTIVE", "Elective"),
                    ("MANDATORY", "Mandatory (PE/NSTP)"),
                    ("TECHNICAL", "Technical/Vocational"),
                ],
                default="PROFESSIONAL",
                help_text="Subject classification",
                max_length=50,
            ),
        ),
    ]
