# Generated by Django 5.2.9 on 2026-02-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0017_subject_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="classification",
            field=models.CharField(
                choices=[("MAJOR", "Major Subject"), ("MINOR", "Minor Subject")],
                default="MINOR",
                help_text="Subject classification",
                max_length=20,
            ),
        ),
    ]
