# Generated by Django 5.2.9 on 2026-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0018_alter_subject_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleslot",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Custom CSS class or hex color for visual coding",
                max_length=50,
                null=True,
            ),
        ),
    ]
