# Generated by Django 5.2.7 on 2026-02-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0019_scheduleslot_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="Whether this subject is visible to all programs (e.g., General Education)",
            ),
        ),
    ]
