# Generated by Django 5.2.7 on 2026-02-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0020_subject_is_global"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[("LECTURE", "Lecture Room"), ("COMPUTER_LAB", "Computer Lab")],
                default="LECTURE",
                max_length=20,
            ),
        ),
    ]
