# Generated by Django 5.2.7 on 2026-02-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0021_alter_room_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="code",
            field=models.CharField(
                help_text="Short code (e.g., BSIT, BSCS)", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(
                help_text="Subject code (e.g., CS101, MATH1)", max_length=50
            ),
        ),
    ]
