# Generated by Django 5.2.7 on 2026-03-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0022_alter_program_code_alter_subject_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="shift",
            field=models.CharField(
                choices=[
                    ("AM", "Morning (AM)"),
                    ("PM", "Afternoon (PM)"),
                    ("FULL_DAY", "Full Day"),
                ],
                default="FULL_DAY",
                help_text="Time-of-day shift for this section (AM, PM, or Full Day)",
                max_length=10,
            ),
        ),
    ]
