# Generated by Django 5.2.7 on 2026-03-07 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_alter_program_code_alter_program_effective_year"),
        ("terms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idn",
                    models.CharField(
                        help_text="e.g., 270001", max_length=15, unique=True
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address_municipality", models.CharField(max_length=100)),
                ("address_barangay", models.CharField(max_length=100)),
                ("address_full", models.TextField(blank=True, null=True)),
                ("contact_number", models.CharField(max_length=20)),
                ("guardian_name", models.CharField(max_length=200)),
                ("guardian_contact", models.CharField(max_length=20)),
                (
                    "student_type",
                    models.CharField(
                        choices=[
                            ("FRESHMAN", "Freshman"),
                            ("TRANSFEREE", "Transferee"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLICANT", "Applicant"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ENROLLED", "Enrolled"),
                            ("INACTIVE", "Inactive"),
                            ("GRADUATED", "Graduated"),
                        ],
                        default="APPLICANT",
                        max_length=15,
                    ),
                ),
                ("appointment_date", models.DateField(blank=True, null=True)),
                ("document_checklist", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academics.curriculumversion",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academics.program",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advising_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("advising_approved_at", models.DateTimeField(blank=True, null=True)),
                ("is_regular", models.BooleanField(default=True)),
                (
                    "year_level",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Cached computed year level for this term",
                        null=True,
                    ),
                ),
                (
                    "monthly_commitment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("enrollment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "advising_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_advisings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrolled_students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="terms.term"
                    ),
                ),
            ],
            options={
                "ordering": ["-enrollment_date"],
                "unique_together": {("student", "term")},
            },
        ),
    ]
