# Generated by Django 5.2.7 on 2026-03-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="previous_school",
            field=models.CharField(
                blank=True,
                help_text="For transferees: Name of the previous school/university",
                max_length=255,
                null=True,
            ),
        ),
    ]
