# Generated by Django 5.2.7 on 2026-03-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_previous_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_advising_unlocked",
            field=models.BooleanField(
                default=False,
                help_text="For transferees: Must be unlocked by registrar after crediting.",
            ),
        ),
    ]
