# Generated by Django 5.2.7 on 2026-03-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_is_advising_unlocked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="address_barangay",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="address_municipality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="guardian_contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="guardian_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
