# Generated by Django 5.2.7 on 2026-03-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_address_barangay_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentenrollment",
            name="advising_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft/Open"),
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                max_length=15,
            ),
        ),
    ]
