# Generated by Django 5.2.7 on 2026-03-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_studentenrollment_advising_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_type",
            field=models.CharField(
                choices=[
                    ("FRESHMAN", "Freshman"),
                    ("TRANSFEREE", "Transferee"),
                    ("CURRENT", "Current Student"),
                ],
                max_length=15,
            ),
        ),
    ]
