# Generated by Django 5.2.12 on 2026-03-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('APPLICANT', 'Applicant'), ('ADMITTED', 'Admitted'), ('REJECTED', 'Rejected'), ('ENROLLED', 'Enrolled'), ('INACTIVE', 'Inactive'), ('GRADUATED', 'Graduated')], default='APPLICANT', max_length=15),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='advising_status',
            field=models.CharField(choices=[('DRAFT', 'Draft/Open'), ('FOR_ADVISING', 'For Advising'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=15),
        ),
    ]
