# Generated by Django 5.2.12 on 2026-04-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='regularity_reason',
            field=models.TextField(blank=True, help_text='Reason for being flagged as irregular', null=True),
        ),
    ]
