# Generated by Django 5.2.12 on 2026-04-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentenrollment_regularity_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='max_units_override',
            field=models.PositiveIntegerField(default=30, help_text='Maximum units allowed for this student in this term (default 30, max 36)'),
        ),
    ]
