# Generated by Django 5.2.12 on 2026-04-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentenrollment_max_units_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='document_checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_advising_unlocked',
            field=models.BooleanField(default=False, help_text='Unlocked by Registrar after document verification, or automatically for transferees upon crediting approval.'),
        ),
    ]
