export const ROLES = {
    ADMIN: 'ADMIN',
    REGISTRAR: 'REGISTRAR',
    HEAD_REGISTRAR: 'HEAD_REGISTRAR',
    ADMISSION: 'ADMISSION',
    CASHIER: 'CASHIER',
    DEAN: 'DEAN',
    PROGRAM_HEAD: 'PROGRAM_HEAD',
    PROFESSOR: 'PROFESSOR',
    STUDENT: 'STUDENT',
};

export const STATUS = {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    ADMITTED: 'ADMITTED',
    REJECTED: 'REJECTED',
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
};
