/**
 * Philippine Locations Data - Bulacan Focus
 * Complete list of municipalities/cities and barangays in Bulacan.
 */

export const PH_LOCATIONS = {
    "Bulacan": {
        "Angat": ["Banaban", "Baybay", "Binagbag", "Donacion", "Encanto", "Laog", "Marungko", "Niugan", "Paltok", "Pulong Yantok", "San Roque", "Santa Cruz", "Santa Lucia", "Santo Cristo", "Sulucan", "Taboc"],
        "Balagtas": ["Borol 1st", "Borol 2nd", "Dalig", "Longos", "Panginay", "Pulong Gubat", "San Juan", "Santol", "Wawa"],
        "Baliuag": ["Bagong Nayon", "Barangca", "Calantipay", "Catulinan", "Concepcion", "Hinukay", "Makinabang", "Matangtubig", "Pagala", "Paitan", "Piel", "Pinagbarilan", "Poblacion", "Sabang", "San Jose", "San Roque", "Santa Barbara", "Santo Cristo", "Santo Niño", "Subic", "Sulivan", "Tangos", "Tarcan", "Tiaong", "Tibag", "Tilapayong", "Virgen delas Flores"],
        "Bocaue": ["Antipona", "Bagumbayan", "Bambang", "Batia", "Biñang 1st", "Biñang 2nd", "Bolacan", "Bundukan", "Bunlo", "Caingin", "Duhat", "Igulot", "Lolomboy", "Poblacion", "Sulucan", "Taal", "Tambobong", "Turo", "Wakas"],
        "Bulakan": ["Bagumbayan", "Balubad", "Bambang", "Matungao", "Maysantol", "Perez", "Pitpitan", "San Francisco", "San Jose", "San Nicolas", "Santa Ana", "Santa Ines", "Taliptip", "Tibig"],
        "Bustos": ["Bonga Mayor", "Bonga Menor", "Buisan", "Camachilihan", "Cambaog", "Catacte", "Liciada", "Malamig", "Malawak", "Poblacion", "San Pedro", "Talampas", "Tanawan", "Tibagan"],
        "Calumpit": ["Balite", "Balungao", "Buguion", "Bulusan", "Calizon", "Calumpang", "Caniogan", "Corazon", "Frances", "Gatbuca", "Gugo", "Iba Este", "Iba O'Este", "Longos", "Meysulao", "Meyto", "Palimbang", "Panducot", "Pio Cruzcosa", "Poblacion", "Pungo", "San Jose", "San Marcos", "San Miguel", "Santa Lucia", "Santo Niño", "Sapang Bayan", "Sergio Bayan", "Sucol"],
        "Doña Remedios Trinidad": ["Bayabas", "Camachile", "Camachin", "Kabayunan", "Kalawakan", "Pulong Sampalok", "Sapang Bulak", "Talbak"],
        "Guiguinto": ["Cutcut", "Daungan", "Ilang-Ilang", "Malis", "Panginay", "Poblacion", "Pritil", "Pulong Gubat", "Santa Cruz", "Santa Rita", "Tabang", "Tabe", "Tiaong", "Tuktukan"],
        "Hagonoy": ["Abulalas", "Carillo", "Iba", "Iba-Ibayo", "Mercado", "Palapat", "Pugad", "Sagrada Familia", "San Agustin", "San Isidro", "San Jose", "San Juan", "San Miguel", "San Nicolas", "San Pablo", "San Pascual", "San Pedro", "San Roque", "San Sebastian", "Santa Cruz", "Santa Elena", "Santa Monica", "Santo Niño", "Santo Rosario", "Tampok", "Tibaguin"],
        "Malolos": ["Anilao", "Atlag", "Babatnin", "Bagna", "Bagong Bayan", "Balayong", "Balite", "Bangkal", "Barihan", "Bulihan", "Bungahan", "Caingin", "Calero", "Caliligawan", "Canalate", "Caniogan", "Catmon", "Cofradia", "Dakila", "Guinhawa", "Ligas", "Liyang", "Longos", "Look 1st", "Look 2nd", "Lugam", "Mabolo", "Mambog", "Masile", "Matimbo", "Mojon", "Namayan", "Niugan", "Pamarawan", "Panasahan", "Pinagbakahan", "San Agustin", "San Gabriel", "San Juan", "San Pablo", "San Vicente", "Santiago", "Santisima Trinidad", "Santo Cristo", "Santo Niño", "Santo Rosario", "Santol", "Sumapang Bata", "Sumapang Matanda", "Taal", "Tikay"],
        "Marilao": ["Abangan Norte", "Abangan Sur", "Ibayo", "Lambakin", "Lias", "Loma de Gato", "Nagbalon", "Patubig", "Poblacion I", "Poblacion II", "Prenza I", "Prenza II", "Santa Rosa I", "Santa Rosa II", "Saog", "Tabing Ilog"],
        "Meycauayan": ["Bagbaguin", "Bahay Pare", "Bancal", "Banga", "Bayugo", "Caingin", "Calvario", "Camalig", "Hulo", "Iba", "Langka", "Lawa", "Libtong", "Liputan", "Longos", "Malhacan", "Pajo", "Pandayan", "Pantoc", "Perez", "Poblacion", "Saint Francis", "Saluysoy", "Tugatog", "Ubihan", "Zamora"],
        "Norzagaray": ["Bangkal", "Baraka", "Bigte", "Bitungol", "Friendship Village Resources", "Matictic", "Minuyan", "Partida", "Pinagtulayan", "Poblacion", "San Lorenzo", "San Mateo", "Tigbe"],
        "Obando": ["Binuangan", "Catanghalan", "Hulo", "Lawa", "Paco", "Pag-asa", "Paliwas", "Panghulo", "Salambao", "San Pascual", "Tawiran"],
        "Pandi": ["Bagbaguin", "Bagong Barrio", "Baka-bakahan", "Bunsuran I", "Bunsuran II", "Bunsuran III", "Cacarong Bata", "Cacarong Matanda", "Cupang", "Malibong Bata", "Malibong Matanda", "Manatal", "Mapulang Lupa", "Masagana", "Masuso", "Pinagkuartelan", "Poblacion", "Real de Cacarong", "San Roque", "Santo Niño", "Siling Bata", "Siling Matanda"],
        "Paombong": ["Binakod", "Kapitangan", "Malumot", "Masukol", "Pinalagdan", "Poblacion", "San Isidro I", "San Isidro II", "San Jose", "San Roque", "San Vicente", "Santa Cruz", "Santo Niño", "Santo Rosario"],
        "Plaridel": ["Agnaya", "Bagong Silang", "Banga I", "Banga II", "Bintog", "Bulihan", "Culianin", "Dampol", "Lagundi", "Lalangan", "Lumang Bayan", "Parulan", "Poblacion", "Rueda", "San Jose", "Santa Ines", "Santo Niño", "Sipat", "Tabang"],
        "Pulilan": ["Balatong A", "Balatong B", "Cutcot", "Dampol I", "Dampol II-A", "Dampol II-B", "Dulong Malabon", "Inaon", "Longos", "Lumbac", "Paltao", "Penabatan", "Poblacion", "Santa Peregrina", "Santo Cristo", "Taal", "Tabon", "Tibag", "Tinejero"],
        "San Ildefonso": ["Akle", "Alagao", "Anyatam", "Bagong Barrio", "Basuit", "Bubulong Malaki", "Bubulong Munti", "Buhol na Mangga", "Bulusukan", "Calasag", "Calawitan", "Casalat", "Gabihan", "Garlang", "Lapnit", "Maasim", "Makapilapil", "Malipampang", "Mataas na Parang", "Matimbubong", "Nabaong Garlang", "Palapala", "Pasong Bangkal", "Pinaod", "Poblacion", "Pulong Tamo", "San Juan", "Santa Catalina Bata", "Santa Catalina Matanda", "Sapang Dayap", "Sapang Putik", "Sapang Putol", "Sumandig", "Telepatio", "Umpucan", "Upig"],
        "San Jose del Monte": ["Assumption", "Bagong Buhay", "Bagong Buhay II", "Bagong Buhay III", "Citrus", "Ciudad Real", "Dulong Bayan", "Fatima", "Fatima II", "Fatima III", "Fatima IV", "Fatima V", "Francisco Homes-Guijo", "Francisco Homes-Mulawin", "Francisco Homes-Narra", "Francisco Homes-Yakal", "Gaya-gaya", "Graceville", "Gumaoc Central", "Gumaoc East", "Gumaoc West", "Kaybanban", "Kaypian", "Lawang Pari", "Maharlika", "Minuyan", "Minuyan II", "Minuyan III", "Minuyan IV", "Minuyan Proper", "Minuyan V", "Muzon", "Paradise III", "Poblacion", "Poblacion I", "Saint Martin de Porres", "San Isidro", "San Manuel", "San Martin", "San Martin II", "San Martin III", "San Martin IV", "San Pedro", "San Rafael", "San Rafael I", "San Rafael III", "San Rafael IV", "San Rafael V", "San Roque", "Santa Cruz", "Santa Cruz II", "Santa Cruz III", "Santa Cruz IV", "Santa Cruz V", "Santo Cristo", "Santo Niño", "Santo Niño II", "Sapang Palay", "Tungkong Mangga"],
        "San Miguel": ["Bagong Pag-asa", "Bagong Silang", "Balaong", "Balite", "Bantog", "Bardias", "Baritan", "Batasan Bata", "Batasan Matanda", "Biak-na-Bato", "Biclat", "Buga", "Buliran", "Bulualto", "Calumpang", "Cambio", "Camias", "Ilog-Bulo", "King Kabayo", "Labne", "Lambakin", "Magmarale", "Malibay", "Maligaya", "Mandile", "Masalipit", "Pacalag", "Paliwasan", "Partida", "Pinambaran", "Poblacion", "Pulong Bayabas", "Pulong Duhat", "Sacdalan", "Salacot", "Salangan", "San Agustin", "San Jose", "San Juan", "San Vicente", "Santa Ines", "Santa Lucia", "Santa Rita Bata", "Santa Rita Matanda", "Sapang", "Sibul", "Tartaro", "Tibagan", "Tigpalas"],
        "San Rafael": ["BMA-Balagtas", "Banca-banca", "Caingin", "Capihan", "Coral na Bato", "Cruz na Daan", "Dagat-dagatan", "Diliman I", "Diliman II", "Libis", "Lico", "Maasim", "Mabalas-balas", "Maguinao", "Maronguillo", "Paco", "Pansumaloc", "Pantubig", "Pasong Bangkal", "Pasong Callos", "Pasong Intsik", "Pinacpinacan", "Poblacion", "Pulo", "Pulong Bayabas", "Salapungan", "Sampaloc", "San Agustin", "San Roque", "Sapang Pahalang", "Talacsan", "Tambubong", "Tukod", "Ulingao"],
        "Santa Maria": ["Bagbaguin", "Balasing", "Buenavista", "Bulac", "Camangyanan", "Catmon", "Cay Pombo", "Caysio", "Guyong", "Lalakhan", "Mag-asawang Sapa", "Mahabang Parang", "Manggahan", "Parada", "Poblacion", "Pulong Buhangin", "San Gabriel", "San Jose Patag", "San Vicente", "Santa Clara", "Santa Cruz", "Silangan", "Tabing Bakod", "Tumana"]
    }
};

export const getProvinces = () => Object.keys(PH_LOCATIONS);
export const getCities = (province) => province ? Object.keys(PH_LOCATIONS[province] || {}) : [];
export const getBarangays = (province, city) => (province && city) ? (PH_LOCATIONS[province]?.[city] || []) : [];
