# Generated by Django 5.2.7 on 2026-03-10 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_alter_program_code_alter_program_effective_year"),
        ("facilities", "0001_initial"),
        ("faculty", "0002_alter_professor_options_and_more"),
        ("scheduling", "0001_initial"),
        ("sections", "0002_section_is_active_section_section_number_and_more"),
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="schedule",
            name="component_type",
            field=models.CharField(
                choices=[("LEC", "Lecture"), ("LAB", "Laboratory")],
                default="LEC",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="days",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="faculty.professor",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="facilities.room",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={("term", "section", "subject", "component_type")},
        ),
    ]
