# Generated by Django 5.2.7 on 2026-03-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professor",
            options={"verbose_name": "Professor", "verbose_name_plural": "Professors"},
        ),
        migrations.AlterModelOptions(
            name="professorsubject",
            options={
                "verbose_name": "Professor Subject",
                "verbose_name_plural": "Professor Subjects",
            },
        ),
    ]
