# Generated by Django 5.2.7 on 2026-03-10 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0002_alter_professor_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("M", "Monday"),
                            ("T", "Tuesday"),
                            ("W", "Wednesday"),
                            ("TH", "Thursday"),
                            ("F", "Friday"),
                            ("S", "Saturday"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        choices=[("AM", "Morning"), ("PM", "Afternoon")], max_length=2
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="faculty.professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professor Availability",
                "verbose_name_plural": "Professor Availabilities",
                "unique_together": {("professor", "day", "session")},
            },
        ),
    ]
