# Generated by Django 5.2.9 on 2025-12-09 12:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_PAYMENT', 'Pending Payment'), ('HOLD', 'On Hold'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_via', models.CharField(choices=[('ONLINE', 'Online Enrollment'), ('TRANSFEREE', 'Transferee Registration'), ('MANUAL', 'Manual Registration')], default='ONLINE', max_length=20)),
                ('monthly_commitment', models.DecimalField(decimal_places=2, help_text='Monthly payment commitment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('first_month_paid', models.BooleanField(default=False, help_text='Whether the first month payment has been completed')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('document_type', models.CharField(choices=[('ID', 'Government ID'), ('FORM_138', 'Form 138 / Report Card'), ('TOR', 'Transcript of Records'), ('GOOD_MORAL', 'Certificate of Good Moral'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('PHOTO', '2x2 Photo'), ('OTHER', 'Other Document')], max_length=20)),
                ('file', models.FileField(upload_to='enrollment_docs/%Y/%m/')),
                ('original_filename', models.CharField(help_text='Original filename when uploaded', max_length=255)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the document has been verified by staff')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Staff notes about this document')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enrollment.enrollment')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment Document',
                'verbose_name_plural': 'Enrollment Documents',
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('name', models.CharField(help_text='Semester name (e.g., "1st Semester", "2nd Semester", "Summer")', max_length=50)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., "2024-2025")', max_length=20)),
                ('start_date', models.DateField(help_text='Semester start date')),
                ('end_date', models.DateField(help_text='Semester end date')),
                ('enrollment_start_date', models.DateField(blank=True, help_text='Date when enrollment opens', null=True)),
                ('enrollment_end_date', models.DateField(blank=True, help_text='Date when enrollment closes', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current active semester')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['-academic_year', '-start_date'],
                'unique_together': {('name', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='enrollment.semester'),
        ),
        migrations.CreateModel(
            name='MonthlyPaymentBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('month_number', models.PositiveIntegerField(help_text='Month number (1-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('required_amount', models.DecimalField(decimal_places=2, help_text='Amount required for this month', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid so far for this month', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_fully_paid', models.BooleanField(default=False, help_text='Whether this month is fully paid')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_buckets', to='enrollment.enrollment')),
            ],
            options={
                'verbose_name': 'Monthly Payment Bucket',
                'verbose_name_plural': 'Monthly Payment Buckets',
                'ordering': ['month_number'],
                'unique_together': {('enrollment', 'month_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'semester')},
        ),
    ]
