# Generated by Django 5.2.9 on 2025-12-09 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_section_sectionsubject_scheduleslot'),
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('status', models.CharField(choices=[('ENROLLED', 'Currently Enrolled'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('INC', 'Incomplete'), ('DROPPED', 'Dropped'), ('CREDITED', 'Credited (Transferee)'), ('RETAKE', 'Retake')], default='ENROLLED', max_length=20)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric grade (1.0 to 5.0)', max_digits=3, null=True)),
                ('is_irregular', models.BooleanField(default=False, help_text='Subject is outside recommended year/semester')),
                ('count_in_gpa', models.BooleanField(default=True, help_text='Whether to include in GPA calculation')),
                ('inc_marked_at', models.DateTimeField(blank=True, help_text='When INC status was set (for expiry calculation)', null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='enrollment.enrollment')),
                ('section', models.ForeignKey(blank=True, help_text='Section for regular enrollment (null for credited subjects)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrollments', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Subject Enrollment',
                'verbose_name_plural': 'Subject Enrollments',
                'ordering': ['subject__year_level', 'subject__semester_number'],
                'unique_together': {('enrollment', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='CreditSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('original_school', models.CharField(help_text='Name of the previous school', max_length=255)),
                ('original_subject_code', models.CharField(help_text='Subject code from the previous school', max_length=50)),
                ('original_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Grade from previous school (optional)', max_digits=3, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this credit (e.g., evaluation notes)')),
                ('credited_by', models.ForeignKey(help_text='Registrar who assigned this credit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_assigned', to=settings.AUTH_USER_MODEL)),
                ('tor_document', models.ForeignKey(blank=True, help_text='Reference to uploaded TOR document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credited_subjects', to='enrollment.enrollmentdocument')),
                ('subject_enrollment', models.OneToOneField(limit_choices_to={'status': 'CREDITED'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_source', to='enrollment.subjectenrollment')),
            ],
            options={
                'verbose_name': 'Credit Source',
                'verbose_name_plural': 'Credit Sources',
            },
        ),
    ]
