# Generated by Django 5.2.7 on 2025-12-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_subjectenrollment_creditsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('PENDING_PAYMENT', 'Pending Payment'), ('HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectenrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Currently Enrolled'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('INC', 'Incomplete'), ('DROPPED', 'Dropped'), ('CREDITED', 'Credited (Transferee)'), ('RETAKE', 'Retake'), ('PENDING_PAYMENT', 'Pending Payment')], default='ENROLLED', max_length=20),
        ),
    ]
