# Generated by Django 5.2.9 on 2025-12-13 13:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_subjectenrollment_creditsource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectenrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Currently Enrolled'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('INC', 'Incomplete'), ('DROPPED', 'Dropped'), ('CREDITED', 'Credited (Transferee)'), ('RETAKE', 'Retake'), ('PENDING_PAYMENT', 'Pending Payment')], default='ENROLLED', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online Banking'), ('GCASH', 'GCash'), ('MAYA', 'Maya'), ('CHECK', 'Check'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('receipt_number', models.CharField(help_text='Unique receipt number (RCV-YYYYMMDD-XXXXX)', max_length=50, unique=True)),
                ('reference_number', models.CharField(blank=True, help_text='External reference number (for online payments)', max_length=100)),
                ('allocated_buckets', models.JSONField(default=list, help_text='List of allocations: [{"bucket_id": uuid, "month": 1, "amount": 1000.00}]')),
                ('is_adjustment', models.BooleanField(default=False, help_text='Whether this is an adjustment transaction (not a regular payment)')),
                ('adjustment_reason', models.TextField(blank=True, help_text='Justification for adjustment (required if is_adjustment=True)')),
                ('processed_at', models.DateTimeField(auto_now_add=True, help_text='When the payment was processed')),
                ('receipt_file', models.FileField(blank=True, help_text='Generated PDF receipt', null=True, upload_to='receipts/%Y/%m/')),
                ('receipt_generated', models.BooleanField(default=False, help_text='Whether the receipt PDF has been generated')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='enrollment.enrollment')),
                ('original_transaction', models.ForeignKey(blank=True, help_text='Original transaction if this is an adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='enrollment.paymenttransaction')),
                ('processed_by', models.ForeignKey(help_text='Cashier who processed this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamMonthMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('exam_period', models.CharField(choices=[('PRELIM', 'Preliminary Exam'), ('MIDTERM', 'Midterm Exam'), ('PREFINAL', 'Pre-Final Exam'), ('FINAL', 'Final Exam')], help_text='The exam period', max_length=20)),
                ('required_month', models.PositiveIntegerField(help_text='Month number (1-6) that must be fully paid', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mapping is active')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_mappings', to='enrollment.semester')),
            ],
            options={
                'verbose_name': 'Exam-Month Mapping',
                'verbose_name_plural': 'Exam-Month Mappings',
                'ordering': ['semester', 'required_month'],
                'unique_together': {('semester', 'exam_period')},
            },
        ),
        migrations.CreateModel(
            name='ExamPermit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('exam_period', models.CharField(choices=[('PRELIM', 'Preliminary Exam'), ('MIDTERM', 'Midterm Exam'), ('PREFINAL', 'Pre-Final Exam'), ('FINAL', 'Final Exam')], help_text='The exam period this permit is for', max_length=20)),
                ('permit_code', models.CharField(help_text='Unique permit code (EXP-YYYYMMDD-XXXXX)', max_length=50, unique=True)),
                ('required_month', models.PositiveIntegerField(help_text='The month that was paid to unlock this permit')),
                ('is_printed', models.BooleanField(default=False, help_text='Whether the permit has been printed')),
                ('printed_at', models.DateTimeField(blank=True, help_text='When the permit was printed', null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_permits', to='enrollment.enrollment')),
                ('printed_by', models.ForeignKey(blank=True, help_text='Who printed the permit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_permits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Permit',
                'verbose_name_plural': 'Exam Permits',
                'ordering': ['-created_at'],
                'unique_together': {('enrollment', 'exam_period')},
            },
        ),
    ]
