# Generated by Django 5.2.9 on 2025-12-13 13:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_add_epic4_payment_exam_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectenrollment',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='When grade was finalized', null=True),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='finalized_by',
            field=models.ForeignKey(blank=True, help_text='Registrar who finalized this grade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='Whether grade has been finalized by registrar'),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='is_retake',
            field=models.BooleanField(default=False, help_text='Whether this is a retake enrollment'),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='original_enrollment',
            field=models.ForeignKey(blank=True, help_text='Original failed enrollment if this is a retake', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retakes', to='enrollment.subjectenrollment'),
        ),
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('previous_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Previous grade value', max_digits=3, null=True)),
                ('new_grade', models.DecimalField(blank=True, decimal_places=2, help_text='New grade value', max_digits=3, null=True)),
                ('previous_status', models.CharField(choices=[('ENROLLED', 'Currently Enrolled'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('INC', 'Incomplete'), ('DROPPED', 'Dropped'), ('CREDITED', 'Credited (Transferee)'), ('RETAKE', 'Retake'), ('PENDING_PAYMENT', 'Pending Payment')], help_text='Status before change', max_length=20)),
                ('new_status', models.CharField(choices=[('ENROLLED', 'Currently Enrolled'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('INC', 'Incomplete'), ('DROPPED', 'Dropped'), ('CREDITED', 'Credited (Transferee)'), ('RETAKE', 'Retake'), ('PENDING_PAYMENT', 'Pending Payment')], help_text='Status after change', max_length=20)),
                ('change_reason', models.TextField(blank=True, help_text='Reason for the change (required for overrides)')),
                ('is_system_action', models.BooleanField(default=False, help_text='Whether this was an automated system action (e.g., INC expiry)')),
                ('is_finalization', models.BooleanField(default=False, help_text='Whether this was a registrar finalization action')),
                ('changed_by', models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_changes', to=settings.AUTH_USER_MODEL)),
                ('subject_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_history', to='enrollment.subjectenrollment')),
            ],
            options={
                'verbose_name': 'Grade History',
                'verbose_name_plural': 'Grade Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SemesterGPA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('gpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated semester GPA', max_digits=3)),
                ('total_units', models.IntegerField(default=0, help_text='Total units included in GPA calculation')),
                ('total_grade_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of (grade × units)', max_digits=8)),
                ('subjects_included', models.IntegerField(default=0, help_text='Number of subjects included in GPA')),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='When GPA was last calculated')),
                ('is_finalized', models.BooleanField(default=False, help_text='Whether all grades are finalized')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpa_record', to='enrollment.enrollment')),
            ],
            options={
                'verbose_name': 'Semester GPA',
                'verbose_name_plural': 'Semester GPAs',
            },
        ),
    ]
