# Generated by Django 5.2.9 on 2025-12-13 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_add_epic5_grade_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('document_code', models.CharField(help_text='Unique document code (DOC-YYYYMMDD-XXXXX)', max_length=50, unique=True)),
                ('document_type', models.CharField(choices=[('TOR', 'Transcript of Records'), ('GOOD_MORAL', 'Good Moral Certificate'), ('ENROLLMENT_CERT', 'Certificate of Enrollment'), ('GRADES_CERT', 'Certificate of Grades'), ('COMPLETION_CERT', 'Certificate of Completion'), ('TRANSFER_CRED', 'Transfer Credentials'), ('HONORABLE_DISMISSAL', 'Honorable Dismissal'), ('DIPLOMA', 'Diploma'), ('OTHER', 'Other Document')], help_text='Type of document released', max_length=30)),
                ('released_at', models.DateTimeField(auto_now_add=True, help_text='When the document was released')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('REISSUED', 'Reissued (superseded)')], default='ACTIVE', help_text='Current status of the document', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the document was revoked', null=True)),
                ('revocation_reason', models.TextField(blank=True, help_text='Reason for revocation (required if revoked)')),
                ('purpose', models.TextField(blank=True, help_text='Purpose of document request')),
                ('copies_released', models.PositiveIntegerField(default=1, help_text='Number of copies released')),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to student)')),
                ('document_file', models.FileField(blank=True, help_text='Optional PDF copy of the document', null=True, upload_to='documents/releases/%Y/%m/')),
                ('released_by', models.ForeignKey(help_text='Registrar who released the document', on_delete=django.db.models.deletion.PROTECT, related_name='documents_released', to=settings.AUTH_USER_MODEL)),
                ('replaces', models.ForeignKey(blank=True, help_text='Document that this one replaces (for reissues)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='enrollment.documentrelease')),
                ('revoked_by', models.ForeignKey(blank=True, help_text='Registrar who revoked the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_revoked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student receiving the document', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='document_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Release',
                'verbose_name_plural': 'Document Releases',
                'ordering': ['-released_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='enrollment__student_433bd9_idx'), models.Index(fields=['released_by', 'released_at'], name='enrollment__release_a0b2bd_idx'), models.Index(fields=['document_type'], name='enrollment__documen_2a6d75_idx')],
            },
        ),
    ]
