# Generated by Django 5.2.7 on 2025-12-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_add_pending_rejected_status'),
        ('enrollment', '0005_add_epic6_document_release'),
    ]

    operations = [
    ]
