# Generated by Django 5.2.9 on 2025-12-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0008_add_dual_approval_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlypaymentbucket",
            name="event_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Event associated with this payment month (e.g., Subject Enrollment, Midterms)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="gradehistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("ENROLLED", "Currently Enrolled"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("INC", "Incomplete"),
                    ("DROPPED", "Dropped"),
                    ("CREDITED", "Credited (Transferee)"),
                    ("RETAKE", "Retake"),
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PENDING_HEAD", "Pending Head Approval"),
                ],
                help_text="Status after change",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gradehistory",
            name="previous_status",
            field=models.CharField(
                choices=[
                    ("ENROLLED", "Currently Enrolled"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("INC", "Incomplete"),
                    ("DROPPED", "Dropped"),
                    ("CREDITED", "Credited (Transferee)"),
                    ("RETAKE", "Retake"),
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PENDING_HEAD", "Pending Head Approval"),
                ],
                help_text="Status before change",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subjectenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ENROLLED", "Currently Enrolled"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("INC", "Incomplete"),
                    ("DROPPED", "Dropped"),
                    ("CREDITED", "Credited (Transferee)"),
                    ("RETAKE", "Retake"),
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PENDING_HEAD", "Pending Head Approval"),
                ],
                default="ENROLLED",
                max_length=20,
            ),
        ),
    ]
