# Generated by Django 5.2.9 on 2026-01-25 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0009_monthlypaymentbucket_event_label_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectenrollment",
            name="enrollment_type",
            field=models.CharField(
                choices=[
                    ("HOME", "Home Section [H]"),
                    ("RETAKE", "Retake/Irregular [R]"),
                    ("OVERLOAD", "Overload [O]"),
                ],
                default="HOME",
                help_text="Classification of this subject enrollment",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="subjectenrollment",
            name="registrar_approved",
            field=models.BooleanField(
                default=False,
                help_text="Whether registrar approval is complete (required for overload)",
            ),
        ),
        migrations.CreateModel(
            name="EnrollmentApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("HEAD", "Department Head"),
                            ("REGISTRAR", "Registrar"),
                            ("ADMIN", "Administrator"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Data Approved"),
                            ("REJECT", "Rejected"),
                            ("OVERRIDE", "Manual Override"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollment_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="enrollment.subjectenrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OverloadRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                ("requested_units", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_overloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enrollment.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overload_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "semester")},
            },
        ),
    ]
