# Generated by Django 5.2.9 on 2026-01-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0010_subjectenrollment_enrollment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="grading_end_date",
            field=models.DateField(
                blank=True, help_text="Date when grading closes", null=True
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="grading_start_date",
            field=models.DateField(
                blank=True, help_text="Date when grading opens", null=True
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="status",
            field=models.CharField(
                choices=[
                    ("SETUP", "Setup"),
                    ("ENROLLMENT_OPEN", "Enrollment Open"),
                    ("ENROLLMENT_CLOSED", "Enrollment Closed"),
                    ("GRADING_OPEN", "Grading Open"),
                    ("GRADING_CLOSED", "Grading Closed"),
                    ("ARCHIVED", "Archived"),
                ],
                default="SETUP",
                help_text="Current status of the semester",
                max_length=20,
            ),
        ),
    ]
