# Generated by Django 5.2.9 on 2026-01-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0011_semester_grading_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradehistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("ENROLLED", "Currently Enrolled"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("INC", "Incomplete"),
                    ("DROPPED", "Dropped"),
                    ("CREDITED", "Credited (Transferee)"),
                    ("RETAKE", "Retake"),
                    ("FOR_RESOLUTION", "For Resolution"),
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PENDING_HEAD", "Pending Head Approval"),
                ],
                help_text="Status after change",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gradehistory",
            name="previous_status",
            field=models.CharField(
                choices=[
                    ("ENROLLED", "Currently Enrolled"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("INC", "Incomplete"),
                    ("DROPPED", "Dropped"),
                    ("CREDITED", "Credited (Transferee)"),
                    ("RETAKE", "Retake"),
                    ("FOR_RESOLUTION", "For Resolution"),
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PENDING_HEAD", "Pending Head Approval"),
                ],
                help_text="Status before change",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subjectenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ENROLLED", "Currently Enrolled"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("INC", "Incomplete"),
                    ("DROPPED", "Dropped"),
                    ("CREDITED", "Credited (Transferee)"),
                    ("RETAKE", "Retake"),
                    ("FOR_RESOLUTION", "For Resolution"),
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PENDING_HEAD", "Pending Head Approval"),
                ],
                default="ENROLLED",
                max_length=20,
            ),
        ),
    ]
