# Generated by Django 5.2.9 on 2026-01-28 06:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0012_alter_gradehistory_new_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "current_grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("proposed_grade", models.DecimalField(decimal_places=2, max_digits=3)),
                ("current_status", models.CharField(max_length=20)),
                ("proposed_status", models.CharField(max_length=20)),
                (
                    "reason",
                    models.TextField(help_text="Reason for grade change request"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REGISTRAR", "Pending Registrar Review"),
                            ("PENDING_HEAD", "Pending Program Head Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING_REGISTRAR",
                        max_length=20,
                    ),
                ),
                ("registrar_notes", models.TextField(blank=True)),
                ("registrar_action_at", models.DateTimeField(blank=True, null=True)),
                ("head_notes", models.TextField(blank=True)),
                ("head_action_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by_head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_resolutions_head",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by_registrar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_resolutions_registrar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_enrollment",
                    models.ForeignKey(
                        help_text="The enrollment record being resolved",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_resolutions",
                        to="enrollment.subjectenrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Resolution",
                "verbose_name_plural": "Grade Resolutions",
                "ordering": ["-created_at"],
            },
        ),
    ]
