# Generated by Django 5.2.9 on 2026-01-28 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0013_graderesolution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectenrollment",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, help_text="When this record was archived", null=True
            ),
        ),
        migrations.AddField(
            model_name="subjectenrollment",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the archival",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subjectenrollment",
            name="failed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When FAILED status was set (for retake eligibility)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subjectenrollment",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this record has been archived",
            ),
        ),
    ]
