# Generated by Django 5.2.9 on 2026-01-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0014_subjectenrollment_archived_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectenrollment",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Professor remarks or requirements for grade resolution",
            ),
        ),
    ]
