# Generated by Django 5.2.9 on 2026-02-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0015_subjectenrollment_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("ACTIVE", "Active"),
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("HOLD", "On Hold"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                    ("ADMITTED", "Admitted (No Subject Enrollment)"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
