# Generated by Django 5.2.7 on 2026-02-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0016_add_admitted_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectenrollment",
            name="grade",
            field=models.CharField(
                blank=True,
                help_text="Grade (1.00 - 5.00, INC, DROPPED)",
                max_length=10,
                null=True,
            ),
        ),
    ]
