# Generated by Django 5.2.7 on 2026-02-20 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0017_alter_subjectenrollment_grade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectenrollment",
            name="is_overridden",
            field=models.BooleanField(
                default=False,
                help_text="Whether this enrollment bypassed standard checks",
            ),
        ),
        migrations.AddField(
            model_name="subjectenrollment",
            name="overridden_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who performed the override",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subject_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subjectenrollment",
            name="override_reason",
            field=models.TextField(
                blank=True, help_text="Justification for the override", null=True
            ),
        ),
    ]
