# Generated by Django 5.2.7 on 2026-02-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0018_subjectenrollment_is_overridden_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graderesolution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_REGISTRAR", "Pending Registrar Review"),
                    ("PENDING_HEAD", "Pending Program Head Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING_HEAD",
                max_length=20,
            ),
        ),
    ]
