# Generated by Django 5.2.7 on 2026-02-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0019_alter_graderesolution_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graderesolution",
            name="current_grade",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="graderesolution",
            name="proposed_grade",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
