# Generated by Django 5.2.7 on 2026-02-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0020_alter_graderesolution_current_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradehistory",
            name="new_grade",
            field=models.CharField(
                blank=True, help_text="New grade value", max_length=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gradehistory",
            name="previous_grade",
            field=models.CharField(
                blank=True, help_text="Previous grade value", max_length=5, null=True
            ),
        ),
    ]
