# Generated by Django 5.2.7 on 2026-03-01 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0021_alter_gradehistory_new_grade_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="graderesolution",
            name="grade_input_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="graderesolution",
            name="grade_input_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Professor or Dean who inputted the grade",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grade_input_resolutions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="graderesolution",
            name="grade_input_comment",
            field=models.TextField(
                blank=True,
                help_text="Optional comment from professor/dean when inputting grade",
            ),
        ),
        migrations.AddField(
            model_name="graderesolution",
            name="registrar_final_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="graderesolution",
            name="submitted_by_dean",
            field=models.BooleanField(
                default=False,
                help_text="True if dean submitted on behalf of inactive/resigned professor",
            ),
        ),
        migrations.AlterField(
            model_name="graderesolution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_REGISTRAR_INITIAL", "Pending Registrar Review"),
                    ("GRADE_INPUT_PENDING", "Waiting for Grade Input"),
                    ("PENDING_HEAD", "Pending Head Approval"),
                    ("PENDING_REGISTRAR_FINAL", "Pending Registrar Final Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING_REGISTRAR_INITIAL",
                max_length=30,
            ),
        ),
    ]
