# Generated by Django 5.2.7 on 2026-03-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0022_grade_resolution_5step_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="admission_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes from admission staff during the admission process",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="assigned_visit_date",
            field=models.DateField(
                blank=True,
                help_text="Assigned date for the student to visit campus for document submission",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_ADMISSION", "Pending Admission"),
                    ("PENDING", "Pending Approval"),
                    ("ACTIVE", "Active"),
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("HOLD", "On Hold"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                    ("ADMITTED", "Admitted (No Subject Enrollment)"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
