# Generated by Django 5.2.7 on 2026-03-01 03:14

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0023_admission_flow_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromissoryNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount promised",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount paid so far against this promissory note",
                        max_digits=10,
                    ),
                ),
                (
                    "covered_months",
                    models.JSONField(
                        default=list,
                        help_text="List of month numbers (1-6) covered by this promissory note",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(help_text="Date by which the student must pay"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("FULFILLED", "Fulfilled"),
                            ("DEFAULTED", "Defaulted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reason for requesting promissory note"),
                ),
                (
                    "terms",
                    models.TextField(
                        blank=True, help_text="Terms and conditions agreed upon"
                    ),
                ),
                (
                    "guarantor_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of parent/guardian guarantor",
                        max_length=200,
                    ),
                ),
                (
                    "guarantor_contact",
                    models.CharField(
                        blank=True,
                        help_text="Contact number of guarantor",
                        max_length=50,
                    ),
                ),
                (
                    "guarantor_relationship",
                    models.CharField(
                        blank=True,
                        help_text="Relationship to student (e.g., Parent, Guardian)",
                        max_length=50,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("defaulted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference_code",
                    models.CharField(
                        help_text="Unique reference code (PN-YYYYMMDD-XXXXX)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registrar/admin who approved the promissory note",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_promissory_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Cashier who created the promissory note",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_promissory_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promissory_notes",
                        to="enrollment.enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promissory Note",
                "verbose_name_plural": "Promissory Notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
